# -*- coding: utf-8 -*-
"""transformer_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wl9N3wFfbW_8eqOhzVAQshzteyWOY8T_
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import copy
from torch.optim import AdamW
from torch.optim.lr_scheduler import LambdaLR, CosineAnnealingLR
from torch.cuda.amp import autocast, GradScaler
from torch.utils.data import DataLoader, Dataset
import numpy as np

# ---------- 1. 配置类（超参数集中管理） ----------
class Config:
    vocab_size = 10000        # 词表大小（实际使用时加载预训练词向量）
    d_model = 512             # 模型维度（隐层大小）
    n_heads = 8               # 多头注意力头数
    d_ff = 2048               # 前馈网络维度（通常为 d_model * 4）
    n_layers = 6              # Transformer 编码器堆叠层数（深一点，能力强）
    max_seq_len = 128         # 最大序列长度
    dropout = 0.1             # 防止过拟合
    num_classes = 2           # 二分类（积极/消极）
    label_smoothing = 0.1     # 标签平滑系数（强力正则化）
    lr = 1e-4                 # 峰值学习率
    warmup_steps = 1000       # 预热步数
    epochs = 10
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

config = Config()

# ---------- 2. 位置编码（Positional Encoding） ----------
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000, dropout=0.1):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        x = x + self.pe[:, :x.size(1), :]
        return self.dropout(x)

# ---------- 3. 多头自注意力（核心组件） ----------
class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, n_heads, dropout=0.1):
        super().__init__()
        assert d_model % n_heads == 0, "d_model 必须能被 n_heads 整除"

        self.d_model = d_model
        self.n_heads = n_heads
        self.d_k = d_model // n_heads

        self.W_q = nn.Linear(d_model, d_model, bias=True)
        self.W_k = nn.Linear(d_model, d_model, bias=True)
        self.W_v = nn.Linear(d_model, d_model, bias=True)
        self.W_o = nn.Linear(d_model, d_model, bias=True)

        self.dropout = nn.Dropout(dropout)

        nn.init.xavier_uniform_(self.W_q.weight)
        nn.init.xavier_uniform_(self.W_k.weight)
        nn.init.xavier_uniform_(self.W_v.weight)
        nn.init.xavier_uniform_(self.W_o.weight)
        if self.W_q.bias is not None:
            nn.init.constant_(self.W_q.bias, 0)
            nn.init.constant_(self.W_k.bias, 0)
            nn.init.constant_(self.W_v.bias, 0)
            nn.init.constant_(self.W_o.bias, 0)

    def forward(self, x, mask=None):
        batch_size, seq_len, _ = x.size()

        Q = self.W_q(x).view(batch_size, seq_len, self.n_heads, self.d_k).transpose(1, 2)
        K = self.W_k(x).view(batch_size, seq_len, self.n_heads, self.d_k).transpose(1, 2)
        V = self.W_v(x).view(batch_size, seq_len, self.n_heads, self.d_k).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_k)

        if mask is not None:
            if mask.dim() == 2:
                mask = mask.unsqueeze(1).unsqueeze(2)
            scores = scores.masked_fill(mask == 0, -1e9)

        attn_weights = F.softmax(scores, dim=-1)
        attn_weights = self.dropout(attn_weights)

        context = torch.matmul(attn_weights, V)
        context = context.transpose(1, 2).contiguous().view(batch_size, seq_len, self.d_model)

        output = self.W_o(context)
        return output

# ---------- 4. 前馈网络（FFN） ----------
class FeedForward(nn.Module):
    def __init__(self, d_model, d_ff, dropout=0.1):
        super().__init__()
        self.linear1 = nn.Linear(d_model, d_ff)
        self.linear2 = nn.Linear(d_ff, d_model)
        self.dropout = nn.Dropout(dropout)

        nn.init.xavier_uniform_(self.linear1.weight)
        nn.init.xavier_uniform_(self.linear2.weight)
        nn.init.constant_(self.linear1.bias, 0)
        nn.init.constant_(self.linear2.bias, 0)

    def forward(self, x):
        x = self.dropout(F.gelu(self.linear1(x)))
        x = self.linear2(x)
        return x

# ---------- 5. Transformer 编码器块（Pre-LN 架构） ----------
class TransformerBlock(nn.Module):
    def __init__(self, d_model, n_heads, d_ff, dropout=0.1):
        super().__init__()
        self.attn = MultiHeadAttention(d_model, n_heads, dropout)
        self.ffn = FeedForward(d_model, d_ff, dropout)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        residual = x
        x = self.norm1(x)
        x = self.attn(x, mask)
        x = self.dropout1(x)
        x = residual + x

        residual = x
        x = self.norm2(x)
        x = self.ffn(x)
        x = self.dropout2(x)
        x = residual + x
        return x

# ---------- 6. 最强完整模型（分类器） ----------
class MaxPowerTransformerForClassification(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config

        self.embedding = nn.Embedding(config.vocab_size, config.d_model, padding_idx=0)
        nn.init.normal_(self.embedding.weight, mean=0, std=0.02)

        self.pos_encoding = PositionalEncoding(config.d_model, config.max_seq_len, config.dropout)

        self.encoder_layers = nn.ModuleList([
            TransformerBlock(config.d_model, config.n_heads, config.d_ff, config.dropout)
            for _ in range(config.n_layers)
        ])

        self.final_norm = nn.LayerNorm(config.d_model)

        self.classifier = nn.Sequential(
            nn.Linear(config.d_model * 2, config.d_model),
            nn.GELU(),
            nn.Dropout(config.dropout),
            nn.Linear(config.d_model, config.num_classes)
        )

        nn.init.xavier_uniform_(self.classifier[0].weight)
        nn.init.xavier_uniform_(self.classifier[3].weight)

    def forward(self, input_ids, mask=None):
        x = self.embedding(input_ids)
        x = self.pos_encoding(x)

        for layer in self.encoder_layers:
            x = layer(x, mask)

        x = self.final_norm(x)

        cls_token = x[:, 0, :]

        if mask is not None:
            mask_expanded = mask.unsqueeze(-1).float()
            sum_embeddings = torch.sum(x * mask_expanded, dim=1)
            seq_lengths = torch.sum(mask_expanded, dim=1).clamp(min=1e-9)
            mean_pool = sum_embeddings / seq_lengths
        else:
            mean_pool = torch.mean(x, dim=1)

        combined = torch.cat([cls_token, mean_pool], dim=1)
        logits = self.classifier(combined)
        return logits

# ---------- 7. 标签平滑损失函数 ----------
def get_loss_fn(label_smoothing=0.1):
    return nn.CrossEntropyLoss(label_smoothing=label_smoothing)

# ---------- 8. 学习率调度器（余弦退火 + 预热） ----------
def get_scheduler(optimizer, d_model, warmup_steps, total_steps):
    def lr_lambda(step):
        if step < warmup_steps:
            return float(step) / float(max(1, warmup_steps))
        progress = float(step - warmup_steps) / float(max(1, total_steps - warmup_steps))
        return max(0.0, 0.5 * (1.0 + math.cos(math.pi * progress)))

    return LambdaLR(optimizer, lr_lambda)

# ---------- 9. 训练函数 ----------
def train_epoch(model, dataloader, optimizer, scheduler, loss_fn, scaler, device, epoch):
    model.train()
    total_loss = 0
    for batch_idx, (inputs, labels) in enumerate(dataloader):
        inputs = inputs.to(device)
        labels = labels.to(device)

        mask = (inputs != 0).to(device)

        with autocast():
            logits = model(inputs, mask)
            loss = loss_fn(logits, labels)

        scaler.scale(loss).backward()

        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        scaler.step(optimizer)
        scaler.update()
        optimizer.zero_grad()
        scheduler.step()

        total_loss += loss.item()

        if batch_idx % 50 == 0:
            print(f"Epoch {epoch} | Batch {batch_idx} | Loss: {loss.item():.4f} | LR: {scheduler.get_last_lr()[0]:.2e}")

    return total_loss / len(dataloader)

# ---------- 10. 虚拟数据运行测试 ----------
if __name__ == "__main__":
    class DummyDataset(Dataset):
        def __init__(self, n_samples=1000):
            self.data = torch.randint(1, 1000, (n_samples, 128))
            self.labels = torch.randint(0, 2, (n_samples,))
        def __len__(self): return len(self.data)
        def __getitem__(self, idx): return self.data[idx], self.labels[idx]

    dataset = DummyDataset()
    dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

    model = MaxPowerTransformerForClassification(config).to(config.device)
    optimizer = AdamW(model.parameters(), lr=config.lr, weight_decay=0.01)
    total_steps = len(dataloader) * config.epochs
    scheduler = get_scheduler(optimizer, config.d_model, config.warmup_steps, total_steps)
    scaler = GradScaler()
    loss_fn = get_loss_fn(config.label_smoothing)

    print("="*50)
    print(f"模型参数总量: {sum(p.numel() for p in model.parameters()):,}")
    print("开始训练最强Transformer...")
    print("="*50)

    for epoch in range(1, config.epochs+1):
        avg_loss = train_epoch(model, dataloader, optimizer, scheduler, loss_fn, scaler, config.device, epoch)
        print(f"Epoch {epoch} 平均损失: {avg_loss:.4f}\n")

    print("训练完成！模型具备极强的语义理解与分类能力。")